Update

diff --git a/bind/.config/etc/init.d/bind9 b/bind/.config/etc/init.d/bind9
--- a/bind/.config/etc/init.d/bind9
+++ b/bind/.config/etc/init.d/bind9
@@ -37,103 +37,103 @@ check_network() {
 
 case "$1" in
     start)
-	log_daemon_msg "Starting domain name service..." "bind9"
+    log_daemon_msg "Starting domain name service..." "bind9"
 
-	modprobe capability >/dev/null 2>&1 || true
+    modprobe capability >/dev/null 2>&1 || true
 
-	# dirs under /run can go away on reboots.
-	mkdir -p /run/named
-	chmod 775 /run/named
-	chown root:bind /run/named >/dev/null 2>&1 || true
+    # dirs under /run can go away on reboots.
+    mkdir -p /run/named
+    chmod 775 /run/named
+    chown root:bind /run/named >/dev/null 2>&1 || true
 
-	if [ ! -x /usr/sbin/named ]; then
-	    log_action_msg "named binary missing - not starting"
-	    log_end_msg 1
-	fi
+    if [ ! -x /usr/sbin/named ]; then
+        log_action_msg "named binary missing - not starting"
+        log_end_msg 1
+    fi
 
-	if ! check_network; then
-	    log_action_msg "no networks configured"
-	    log_end_msg 1
-	fi
+    if ! check_network; then
+        log_action_msg "no networks configured"
+        log_end_msg 1
+    fi
 
-	if start-stop-daemon --start --oknodo --quiet --exec /usr/sbin/named \
-		--pidfile ${PIDFILE} -- $OPTIONS; then
-	    if [ "X$RESOLVCONF" != "Xno" ] && [ -x /sbin/resolvconf ] ; then
-		echo "nameserver 127.0.0.1" | /sbin/resolvconf -a lo.named
-	    fi
-	    log_end_msg 0
-	else
-	    log_end_msg 1
-	fi
+    if start-stop-daemon --start --oknodo --quiet --exec /usr/sbin/named \
+        --pidfile ${PIDFILE} -- $OPTIONS; then
+        if [ "X$RESOLVCONF" != "Xno" ] && [ -x /sbin/resolvconf ] ; then
+        echo "nameserver 127.0.0.1" | /sbin/resolvconf -a lo.named
+        fi
+        log_end_msg 0
+    else
+        log_end_msg 1
+    fi
     ;;
 
     stop)
-	log_daemon_msg "Stopping domain name service..." "bind9"
-	if ! check_network; then
-	    log_action_msg "no networks configured"
-	    log_end_msg 1
-	fi
+    log_daemon_msg "Stopping domain name service..." "bind9"
+    if ! check_network; then
+        log_action_msg "no networks configured"
+        log_end_msg 1
+    fi
 
-	if [ "X$RESOLVCONF" != "Xno" ] && [ -x /sbin/resolvconf ] ; then
-	    /sbin/resolvconf -d lo.named
-	fi
-	pid=$(/usr/sbin/rndc stop -p | awk '/^pid:/ {print $2}') || true
-	if [ -z "$pid" ]; then		# no pid found, so either not running, or error
-	    pid=$(pgrep -f ^/usr/sbin/named) || true
-	    start-stop-daemon --stop --oknodo --quiet --exec /usr/sbin/named \
-		    --pidfile ${PIDFILE} -- $OPTIONS
-	fi
-	if [ -n "$pid" ]; then
-	    sig=0
-	    n=1
-	    while kill -$sig $pid 2>/dev/null; do
-		if [ $n -eq 1 ]; then
-		    echo "waiting for pid $pid to die"
-		fi
-		if [ $n -eq 11 ]; then
-		    echo "giving up on pid $pid with kill -0; trying -9"
-		    sig=9
-		fi
-		if [ $n -gt 20 ]; then
-		    echo "giving up on pid $pid"
-		    break
-		fi
-		n=$(($n+1))
-		sleep 1
-	    done
-	fi
-	log_end_msg 0
+    if [ "X$RESOLVCONF" != "Xno" ] && [ -x /sbin/resolvconf ] ; then
+        /sbin/resolvconf -d lo.named
+    fi
+    pid=$(/usr/sbin/rndc stop -p | awk '/^pid:/ {print $2}') || true
+    if [ -z "$pid" ]; then        # no pid found, so either not running, or error
+        pid=$(pgrep -f ^/usr/sbin/named) || true
+        start-stop-daemon --stop --oknodo --quiet --exec /usr/sbin/named \
+            --pidfile ${PIDFILE} -- $OPTIONS
+    fi
+    if [ -n "$pid" ]; then
+        sig=0
+        n=1
+        while kill -$sig $pid 2>/dev/null; do
+        if [ $n -eq 1 ]; then
+            echo "waiting for pid $pid to die"
+        fi
+        if [ $n -eq 11 ]; then
+            echo "giving up on pid $pid with kill -0; trying -9"
+            sig=9
+        fi
+        if [ $n -gt 20 ]; then
+            echo "giving up on pid $pid"
+            break
+        fi
+        n=$(($n+1))
+        sleep 1
+        done
+    fi
+    log_end_msg 0
     ;;
 
     reload|force-reload)
-	log_daemon_msg "Reloading domain name service..." "bind9"
-	if ! check_network; then
-	    log_action_msg "no networks configured"
-	    log_end_msg 1
-	fi
+    log_daemon_msg "Reloading domain name service..." "bind9"
+    if ! check_network; then
+        log_action_msg "no networks configured"
+        log_end_msg 1
+    fi
 
-	/usr/sbin/rndc reload >/dev/null && log_end_msg 0 || log_end_msg 1
+    /usr/sbin/rndc reload >/dev/null && log_end_msg 0 || log_end_msg 1
     ;;
 
     restart)
-	if ! check_network; then
-	    log_action_msg "no networks configured"
-	    exit 1
-	fi
+    if ! check_network; then
+        log_action_msg "no networks configured"
+        exit 1
+    fi
 
-	$0 stop
-	$0 start
+    $0 stop
+    $0 start
     ;;
 
     status)
-    	ret=0
-	status_of_proc -p ${PIDFILE} /usr/sbin/named bind9 2>/dev/null || ret=$?
-	exit $ret
-	;;
+        ret=0
+    status_of_proc -p ${PIDFILE} /usr/sbin/named bind9 2>/dev/null || ret=$?
+    exit $ret
+    ;;
 
     *)
-	log_action_msg "Usage: /etc/init.d/bind9 {start|stop|reload|restart|force-reload|status}"
-	exit 1
+    log_action_msg "Usage: /etc/init.d/bind9 {start|stop|reload|restart|force-reload|status}"
+    exit 1
     ;;
 esac
 
