Update

diff --git a/python/Dockerfile b/python/Dockerfile
--- a/python/Dockerfile
+++ b/python/Dockerfile
@@ -28,6 +28,7 @@ RUN         find / -name 'libpython*.so*' -type f
 
 RUN         /lib64/ld-linux-x86-64.so.2 --library-path $PATH_APP/python $PATH_APP/python/python -V || echo "Failed python version test."
 RUN         /lib64/ld-linux-x86-64.so.2 --library-path $PATH_APP/python $PATH_APP/python/python -c "import ssl" || echo "Failed python openssl test."
+RUN         /lib64/ld-linux-x86-64.so.2 --library-path $PATH_APP/python $PATH_APP/python/python -c "import zlib" || echo "Failed python zlib test."
 RUN         /lib64/ld-linux-x86-64.so.2 --library-path $PATH_APP/python $PATH_APP/python/python -c "import sqlite3" || echo "Failed python sqlite3 test."
 
 RUN         /lib64/ld-linux-x86-64.so.2 --library-path $PATH_APP/python $PATH_APP/python/python -E -S -m sysconfig --generate-posix-vars
